name: Deploy CloudFormation Stack

on:
  pull_request:
    branches:
      - main
      - develop
    types: [opened, reopened, closed]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Deploy CloudFormation stack
        run: aws cloudformation deploy --template-file template.yml --stack-name my-stack --capabilities CAPABILITY_IAM
